/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART1RXSRC_UART_RX 0x00u /*!<@brief UART1 Receive Data Source Select: UART1_RX pin */
#define SOPT5_UART1TXSRC_UART_TX 0x00u /*!<@brief UART1 Transmit Data Source Select: UART1_TX pin */

/*! @name PORTB0 (number 35), LED
  @{ */
#define BOARD_INITPINS_LED_BACKLIGHT_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LED_BACKLIGHT_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LED_BACKLIGHT_PIN 0U     /*!<@brief PORTB pin index: 0 */
                                                /* @} */

/*! @name PORTB1 (number 36), Buttons R1
  @{ */
#define BOARD_INITPINS_BUTTON_R1_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_BUTTON_R1_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_BUTTON_R1_PIN 1U     /*!<@brief PORTB pin index: 1 */
                                            /* @} */

/*! @name PORTB2 (number 37), Buttons R2
  @{ */
#define BOARD_INITPINS_BUTTON_R2_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_BUTTON_R2_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_BUTTON_R2_PIN 2U     /*!<@brief PORTB pin index: 2 */
                                            /* @} */

/*! @name PORTB3 (number 38), Buttons R3
  @{ */
#define BOARD_INITPINS_BUTTON_R3_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_BUTTON_R3_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_BUTTON_R3_PIN 3U     /*!<@brief PORTB pin index: 3 */
                                            /* @} */

/*! @name PORTB16 (number 39), Buttons L1
  @{ */
#define BOARD_INITPINS_BUTTON_L1_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_BUTTON_L1_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_BUTTON_L1_PIN 16U    /*!<@brief PORTB pin index: 16 */
                                            /* @} */

/*! @name PORTB17 (number 40), Buttons L2
  @{ */
#define BOARD_INITPINS_BUTTON_L2_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_BUTTON_L2_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_BUTTON_L2_PIN 17U    /*!<@brief PORTB pin index: 17 */
                                            /* @} */

/*! @name PORTB18 (number 41), Buttons L3
  @{ */
#define BOARD_INITPINS_BUTTON_L3_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_BUTTON_L3_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_BUTTON_L3_PIN 18U    /*!<@brief PORTB pin index: 18 */
                                            /* @} */

/*! @name PORTB19 (number 42), Buttons L4
  @{ */
#define BOARD_INITPINS_BUTTON_L4_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_BUTTON_L4_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_BUTTON_L4_PIN 19U    /*!<@brief PORTB pin index: 19 */
                                            /* @} */

/*! @name PORTC4 (number 49), SCS (Radio Module)
  @{ */
#define BOARD_INITPINS_SOFT_SPI_CS_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_SOFT_SPI_CS_PIN 4U     /*!<@brief PORTC pin index: 4 */
                                              /* @} */

/*! @name PORTC5 (number 50), SCK (Radio Module)
  @{ */
#define BOARD_INITPINS_SOFT_SPI_SCK_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_SOFT_SPI_SCK_PIN 5U     /*!<@brief PORTC pin index: 5 */
                                               /* @} */

/*! @name PORTC6 (number 51), SDIO (Radio Module)
  @{ */
#define BOARD_INITPINS_SOFT_SPI_MOSI_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_SOFT_SPI_MOSI_PIN 6U     /*!<@brief PORTC pin index: 6 */
                                                /* @} */

/*! @name PORTD0 (number 57), SwA
  @{ */
#define BOARD_INITPINS_SwA_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_SwA_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_SwA_PIN 0U     /*!<@brief PORTD pin index: 0 */
                                      /* @} */

/*! @name PORTD4 (number 61), SwD
  @{ */
#define BOARD_INITPINS_SwD_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_SwD_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_SwD_PIN 4U     /*!<@brief PORTD pin index: 4 */
                                      /* @} */

/*! @name PORTD3 (number 60), GIO1 (Radio Module)
  @{ */
#define BOARD_INITPINS_SOFT_SPI_MISO_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_SOFT_SPI_MISO_PIN 3U     /*!<@brief PORTD pin index: 3 */
                                                /* @} */

/*! @name PORTA5 (number 27), Bind
  @{ */
#define BOARD_INITPINS_Bind_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_Bind_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_Bind_PIN 5U     /*!<@brief PORTA pin index: 5 */
                                       /* @} */

/*! @name PORTA12 (number 28), Buzzer
  @{ */
#define BOARD_INITPINS_Buzzer_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_Buzzer_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_Buzzer_PIN 12U    /*!<@brief PORTA pin index: 12 */
                                         /* @} */

/*! @name PORTD2 (number 59), spare? (unmarked test pad)
  @{ */
#define BOARD_INITPINS_SPARE_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_SPARE_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_SPARE_PIN 2U     /*!<@brief PORTD pin index: 2 */
                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
