/*
 * Copyright (c) 2013 - 2016, Freescale Semiconductor, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * o Redistributions of source code must retain the above copyright notice, this list
 *   of conditions and the following disclaimer.
 *
 * o Redistributions in binary form must reproduce the above copyright notice, this
 *   list of conditions and the following disclaimer in the documentation and/or
 *   other materials provided with the distribution.
 *
 * o Neither the name of Freescale Semiconductor, Inc. nor the names of its
 *   contributors may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * This is template for main module created by New Kinetis SDK 2.x Project Wizard. Enjoy!
 **/
#include <fsl_debug_console.h>
#include "board.h"
#include "pin_mux.h"
#include "clock_config.h"

#include "timer.h"
#include "delay.h"
#include "lcd.h"
#include "sound.h"
#include "console.h"
#include "screen.h"
#include "debug.h"
#include "adc.h"
#include "backlight.h"
#include "buttons.h"
#include "drv_time.h"
#include "flash.h"
#include "storage.h"
#include "gui.h"
#include "multiprotocol.h"

//------------------------------------------------------------------------------
// Forward declarations
static void tests();

//------------------------------------------------------------------------------
void required_updates()
{
    // Call time_update() once at start of every loop
    time_update();

    // Update our multiprotocol system
    multiprotocol_update();
    
    // Query state of buttons and perform debounce
    buttons_update();

    // Retrieve ADC values for sticks and mult-position switches
    adc_update();

    sound_update();
    led_backlight_update();
}

//------------------------------------------------------------------------------
int main(void)
{
    /* Init board hardware. */
    BOARD_InitPins();
    BOARD_BootClockRUN();
    BOARD_SysTick();

    // Do not execute BOARD_InitPeripherals()
    // It is auto-generated by MCUXpresso Config Tools and is only used for reference
    // 
//XXX    BOARD_InitPeripherals();

    // Prevent A7105 module from being selected during SPI
    {
        // Set CS for the A7105 module to always be inactive (HIGH)
        gpio_pin_config_t pin_config_output_high = {
            kGPIO_DigitalOutput, 1
        };
        GPIO_PinInit(BOARD_INITPINS_SOFT_SPI_CS_A7105_GPIO, BOARD_INITPINS_SOFT_SPI_CS_A7105_PIN, &pin_config_output_high); // PORTC, 4
    }

    multiprotocol_init();
    timer_init();
    lcd_init();
    led_backlight_init();
    flash_init();
    storage_init();
    screen_init();
    console_init();
    debug_init();
    buttons_init();
    sound_init();
    int needStickCalibration = adc_init();
    if (needStickCalibration)
    {
        adc_calibrate_sticks();
    }

    // Perform required updates for a little bit before fully starting up
    // this allows an gui code to properly query adc or buttons
    for (int i=0; i<5; i++)
    {
        required_updates();
        delay_ms(20);
    }

    // Call buttons_update() once so we can use button_raw_state()
    buttons_update();
    if (button_raw_state(kBtn_ThrottleU))
    {
        tests();
    }

    gui_init();
    gui_loop();
    return 0;
}

//------------------------------------------------------------------------------
static void tests()
{
    int testNumber = 0;
    while (1)
    {
        // Call the required update functions of various systems
        required_updates();

        // Advance to next test if down button was activated
        if (button_toggledActive(kBtn_Down))
        {
            testNumber++;
        }
        switch (testNumber)
        {
            case 0:
                buttons_test();
                break;

            case 1:
                adc_test();
                break;

            case 2:
                delay_test();
                break;

            case 3:
                millis_test();
                break;

            default:
                testNumber = 0;
                break;
        }
//        PRINTF("loop time: %d\n", micros_realtime() - micros_this_frame());
    }
}


